### ISSUE TITLE
[BUG] Currency component - Unique validation does not work

### ISSUE THREAD

**Issue by phucduong86** [formio/formio#1054]
## Environment
Please provide as many details as you can:

- Hosting type (Tested on both)
  - [x] Form.io: Application: 7.0.38, Renderer: 4.11.1
  - [X] Local deployment
    - Version: Application: 7.0.8, Renderer: 4.9.27-rc.4 

## Steps to Reproduce
1. Create a new form
2. Add a Currency component
3. Enable Unique validation on the component
4. Create a submission (eg: 24)
5. Create another submission with the same data

## Expected behavior
Server validation (field must be unique) should return and error on second submission

## Observed behavior
Submission successful.

## Screenshot

![image](https://user-images.githubusercontent.com/21692768/89464836-15fc7700-d73f-11ea-8a96-0b244d3b4a35.png)

****
![image](https://user-images.githubusercontent.com/21692768/89464877-2a407400-d73f-11ea-9675-94e17ca65cc3.png)

**Comment by wag110894** [comment]
Hello @phucduong86 Thanks for reaching out! This is a known issue on our side. For reference, the ticket number is: FJS-970. We will let you know once this issue has been resolved.

Thank you.

**Comment by jhen1422** [comment]
This issue should be resolved in formio.js 4.12.1

**Comment by DaveBagler** [comment]
This is still a problem with portal 7.1.4 and library 4.14.0-rc.18.

**Comment by jhen1422** [comment]
@DaveBagler 
While we don't have an environment with the mentioned versions, I can confirm this issue is resolved using the following environment.

API 7.2.0
FJS 4.14.0-rc.26
