### ISSUE TITLE
Can not start formio with docker-compose, like described in readme

### ISSUE THREAD

**Issue by ppfeiler** [formio/formio#1717]
**Describe the bug**
I tried to start formio with docker, like described in the readme.

**Version/Branch**
Current 3.5.x branch

**To Reproduce**
- Checkout the project
- Run `npm install`
- Run `docker-compose up`

Now when formio should start, you should see the following error message:

``` 
Attaching to formio_formio_1
formio_1  | 
formio_1  | Mount client application
formio_1  |   formio:db Opening new connection to mongodb://mongo:27017/formio +0ms
formio_1  |   __  __                          _       __
formio_1  |  / / / _| ___  _ __ _ __ ___     (_) ___  \ \
formio_1  | / / | |_ / _ \| '__| '_ ` _ \    | |/ _ \  \ \
formio_1  | \ \ |  _| (_) | |  | | | | | | _ | | (_) | / /
formio_1  |  \_\|_|  \___/|_|  |_| |_| |_|(_)|_|\___/ /_/
formio_1  | 
formio_1  | Welcome to the Form.io application server!
formio_1  | 
formio_1  |   - Help: https://help.form.io
formio_1  |   - Code: https://github.com/formio
formio_1  |   - Love: https://form.io
formio_1  | 
formio_1  |   formio:db Connection successful +22ms
formio_1  |   formio:db Schema collection opened +1ms
formio_1  | Checking for db setup.
formio_1  |   formio:db Collections found: 7 +70ms
formio_1  |  > Setup complete.
formio_1  | 
formio_1  | Determine MongoDB compatibility.
formio_1  | Collation indexes are supported.
formio_1  |   formio:db Update found: 1.0.0.js +87ms
formio_1  |   formio:db Update found: 1.1.0.js +0ms
formio_1  |   formio:db Update found: 2.0.0.js +0ms
formio_1  |   formio:db Update found: 2.0.1.js +1ms
formio_1  |   formio:db Update found: 2.1.0.js +0ms
formio_1  |   formio:db Update found: 2.2.0.js +0ms
formio_1  |   formio:db Update found: 2.2.1.js +0ms
formio_1  |   formio:db Update found: 2.2.2.js +0ms
formio_1  |   formio:db Update found: 2.3.0.js +1ms
formio_1  |   formio:db Update found: 2.3.1.js +0ms
formio_1  |   formio:db Update found: 2.3.2.js +0ms
formio_1  |   formio:db Update found: 2.4.0.js +0ms
formio_1  |   formio:db Update found: 2.4.1.js +0ms
formio_1  |   formio:db Update found: 2.4.2.js +0ms
formio_1  |   formio:db Update found: 2.4.3.js +0ms
formio_1  |   formio:db Update found: 3.0.0.js +0ms
formio_1  |   formio:db Update found: 3.0.1.js +1ms
formio_1  |   formio:db Update found: 3.0.2.js +0ms
formio_1  |   formio:db Update found: 3.0.3.js +0ms
formio_1  |   formio:db Update found: 3.0.4.js +0ms
formio_1  |   formio:db Update found: 3.0.5.js +0ms
formio_1  |   formio:db Update found: 3.0.6.js +0ms
formio_1  |   formio:db Update found: 3.0.7.js +0ms
formio_1  |   formio:db Update found: 3.0.8.js +0ms
formio_1  |   formio:db Update found: 3.0.9.js +1ms
formio_1  |   formio:db Update found: 3.1.0.js +0ms
formio_1  |   formio:db Update found: 3.1.1.js +0ms
formio_1  |   formio:db Update found: 3.1.2.js +0ms
formio_1  |   formio:db Update found: 3.1.3.js +0ms
formio_1  |   formio:db Update found: 3.1.4.js +0ms
formio_1  |   formio:db Update found: 3.1.5.js +0ms
formio_1  |   formio:db Final updates +2ms
formio_1  |   formio:db [
formio_1  |   formio:db   {
formio_1  |   formio:db     _id: new ObjectId("65eeda80e5e735af856ca31f"),
formio_1  |   formio:db     key: 'formio',
formio_1  |   formio:db     isLocked: false,
formio_1  |   formio:db     version: '3.1.4'
formio_1  |   formio:db   }
formio_1  |   formio:db ] +7ms
formio_1  |   formio:db Lock engaged +17ms
formio_1  | Checking for Config Forms updates.
formio_1  |  > No config forms updates found.
formio_1  | 
formio_1  | Checking for db schema updates.
formio_1  |   formio:db Current database (3.1.4) and Pending code sversions (3.1.4) are the same. +2ms
formio_1  |  > No updates found.
formio_1  | 
formio_1  |   formio:db Lock unlocked +8ms
formio_1  |   formio:db Lock unlocked +6ms
formio_1  | Initializing API Server.
formio_1  | (node:1) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
formio_1  | (Use `node --trace-deprecation ...` to show where the warning was created)
formio_1  |  > Mongo connection established.
formio_1  | (node:1) UnhandledPromiseRejectionWarning: Error: Cannot find module 'node:domain'
formio_1  | Require stack:
formio_1  | - /app/node_modules/formio-workers/Formio.js
formio_1  | - /app/node_modules/formio-workers/Worker.js
formio_1  | - /app/node_modules/formio-workers/Thread.js
formio_1  | - /app/src/worker/Worker.js
formio_1  | - /app/src/util/email.js
formio_1  | - /app/src/actions/EmailAction.js
formio_1  | - /app/src/actions/actions.js
formio_1  | - /app/index.js
formio_1  | - /app/server.js
formio_1  | - /app/main.js
formio_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
formio_1  |     at Function.Module._load (internal/modules/cjs/loader.js:730:27)
formio_1  |     at Module.require (internal/modules/cjs/loader.js:957:19)
formio_1  |     at require (internal/modules/cjs/helpers.js:88:18)
formio_1  |     at Object.<anonymous> (/app/node_modules/formio-workers/Formio.js:6:16)
formio_1  |     at Module._compile (internal/modules/cjs/loader.js:1068:30)
formio_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
formio_1  |     at Module.load (internal/modules/cjs/loader.js:933:32)
formio_1  |     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
formio_1  |     at Module.require (internal/modules/cjs/loader.js:957:19)
formio_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
formio_1  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
Formio starts and is reachable

**Additional context**
I am running nodejs 14.17.0

**Comment by lane-formio** [comment]
I'm unable to reproduce this following your exact steps. Can you try deleting the node_modules and install again?

**Comment by carlotodeschini** [comment]
Same problem to me.
- OS: linux
- docker compose: 2.25.0
- npm: 9.6.7
- node: 18.17.1

I needed to comment also Dockerfile line #36 to reach this point:

> #RUN npm ci --prefix=$NPM_PACKAGES

**Comment by molotow11** [comment]
Same here
`(node:1) UnhandledPromiseRejectionWarning: Error: Cannot find module 'node:domain'`

**Comment by datzash2003** [comment]
Same issue here

**Comment by mathismoder** [comment]
I think https://github.com/formio/formio/pull/1484/files should resolve the issues, that PR sure is getting old :) 

Otherwise you can try the attached patch, which:
- uses the existing yarn.lock, so
- doesn't need node_modules populated before building (in fact you should remove it)
- updates node to 18 LTS (as the one included is EOL since years)
- doesn't mount the whole folder for performance reasons

Patch: [fix_and_update.patch](https://github.com/formio/formio/files/14945927/fix_and_update.patch)

**Comment by brendanbond** [comment]
Hi all thanks for reporting, we've gone ahead and decoupled the docker build from the host machine [here](https://github.com/formio/formio/pull/1703). (Cc: @ppfeiler I wasn't aware of your similar PR, but thanks so much for opening that!!!) Can we try to clone and run the docker build from `master` and see if this issue persists? 

Thanks

**Comment by lukirs95** [comment]
Hi

Clone and Run like in readme still fails in master branch. Applying the patch from @mathismoder fixes the issue.

Error occurs at:

``` docker
RUN npm ci --prefix=/.npm-packages

npmERR! Cannot read property '@formio/node-fetch-http-proxy' of undefined
npmERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2024-04-22T10_20_59_942Z-debug.log
```

**Comment by brendanbond** [comment]
@lukirs95 did you pull down the latest changes to the master branch? As I mentioned, those changes should have already been applied, `RUN npm ci --prefix=/.npm-packages` no longer even appears in the Dockerfile. I'm closing this issue for now, please let us know if you're continuing to see issues once you pull down the latest changes from the `master` branch of this repository. (Also keep in mind that the default branch is `3.5.x` and that an official release will be coming soon).
