### ISSUE TITLE
[BUG] Various settings are not display properly on the portal

### ISSUE THREAD

**Issue by phucduong86** [formio/formio#970]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: Docker container formio/formio-enterprise 6.9.28
    - Portal version: Application: 7.0.0, Renderer: 4.9.19
- Browser: Chrome
- Browser version: 80.0.3987.149 (Official Build) (64-bit)

## Steps to Reproduce

Show Header settings does not persists
1.	Create a new form
2.	Click Launch tab
3.	Uncheck Show Header and click Make Public
4.	Reload the page
-	Expected: Show Header setting persists
-	What we got: Show Header is checked again

5.	Uncheck the Show Header setting again
6.	Reload the page
-	Expected: Show Header setting persists
-	What we got: Show Header is checked again

Custom Secret Validation does not persists:
This happens on multiple Components
Steps:
1.	Create a new field (eg Text Field)
2.	Click Validation -> Custom Validation
3.	Enter validation logic (eg: valid = (input === 'Joe') ? true: 'you are not Joe'; )
4.	Check the “Secret Validation” box
5.	Save the form
6.	Reload the form edit page
7.	Click on Text Field setting -> Validation and expand Custom Validation
-	Expected: validation logic is still there
-	What we see: the text area for custom validation code is empty

Radio  Component – Data Value does not persists
Steps:
1.	Create a new Radio Component field
2.	On the data tab enter:
Label: Test Value
Value: Test Value
3.	Save the component
4.	Save the form
5.	Click Edit the Radio Component -> Data tab
-	Expected: Value should be ‘Test Value’
-	What we see: Value display as ‘testValue’

I’ve verified API endpoint and all these values were stored properly in the form Definition. However, if it changes when user click on it, it would be changed and wiped out.

**Comment by wag110894** [comment]
@phucduong86,
Thank you for reaching out

**Show Header settings does not persists**
Go into your Access settings and set Create Own Submissions to Anonymous. This should resolve this issue.

**Custom Secret Validation does not persists:**
We are not able to replicate this issue on our side. We are seeing the custom validations as expected. Can you try using the latest?


**Radio Component – Data Value does not persists**
This is a known issue on our side. We added you to the ticket. For reference the ticket is FJS-869.

**Comment by phucduong86** [comment]
@wag110894  Thank you for your response.
We've upgraded the portal to latest version (Docker Image tag 6.9.29,  Application: 7.0.1, Renderer: 4.9.20) and it still persists.

**Show Header settings does not persists**
I tried various combination of Create Own Submissions : "Anonymous" "Everyone" "Anonymous, Authenticated, Administrator" and the issue is not resolve.
This is minor because we can change the prams in the link but would be nice if it is resolved.

**Custom Secret Validation does not persists:**
This only happens when the "Secret Validation" checkbox is Checked. Can you please verify?

**Radio Component – Data Value does not persists**
How can I check the status of the ticket and would I get a notification when it's resolved?

Thank you again.

**Comment by wag110894** [comment]
@phucduong86 

Thank you for providing more information.

**Show Header settings does not persist.** 
You should be able to just add the Anonymous and it should work. You may need to open in an Incognito Window. 

**Custom Secret Validation does not persist:**
Here is a video of the Anonymous setting working as well as the Secret Validation persisting: https://share.getcloudapp.com/lluDwqWQ

**Radio Component – Data Value does not persist**
We have tagged you on the Ticket and we will let you know once this issue is resolved in the thread. That ticket number again is FJS-869.

**Comment by wag110894** [comment]
@phucduong86 

Thanks for sending over the email. 
**Shower Header settings does not persist.** 
Thank you for the video on this item.
The Show Header setting inside the launch page does not save, so this is working as expected.

Custom Secret Validation does not persist:
Can you provide a new video as this gif was sent as individual images?

**Comment by phucduong86** [comment]
Hi,

The gif must have been compressed sorry about that.
Here it is:
https://www.dropbox.com/s/tny5ojzuwvptkon/customvalidation.gif?dl=0

**Comment by wag110894** [comment]
Dropbox is not showing the gif correctly either.

**Comment by phucduong86** [comment]
Hi,

You should be able to download it and view it. 
I don't think Dropbox actually play the gif

**Comment by wag110894** [comment]
This is still downloading as individual pages. We are not able to replicate this issue on the latest version. We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. 

Please contact support@form.io for information on a support package.

**Comment by phucduong86** [comment]
Hi,

Please open the gif with the Chrome browser, I've tried with various computer on different network and it works fine.
This issue happens after we upgraded from 6.7.14 version to 6.9.29.

- It does not happen with new project or new form
- It happens on all forms in the existing project (created prior to update)

**Comment by wag110894** [comment]
This has been tested on a form that I created last year and it is working as expected.
